services:

  wordpress:
    build:
      context: .
      dockerfile_inline: |
        FROM wordpress:${WORDPRESS_TAG:-latest}
        COPY --link wordpress/custom-routing.php /usr/src/wordpress/custom-routing.php
    image: emanu11/wordpress-dso:latest
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: ${DB_PASS:?}
      WORDPRESS_DB_NAME: wpdb
      WORDPRESS_CONFIG_EXTRA: "require_once '/var/www/html/custom-routing.php';"
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test:
        - CMD
        - bash
        - -c
        - curl -sf http://localhost/wp-json/
      start_interval: 1s
      start_period: 420s
    volumes:
      - wordpress:/var/www/html

  wordpress-config:
    image: wordpress:cli
    user: "33:33"
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: ${DB_PASS:?}
      WORDPRESS_DB_NAME: wpdb
    depends_on:
      wordpress:
        condition: service_started
    volumes:
      - wordpress:/var/www/html
    command: >
      sh -c '
      wp core is-installed || wp core install \
        --url="http://localhost:8080" \
        --title="Dummy WP" \
        --admin_user="admin" \
        --admin_password="${WP_ADMIN_PASS:-secret}" \
        --admin_email="admin@wp.com" \
        --skip-email
      '

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: wpdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: ${DB_PASS:?}
      MYSQL_RANDOM_ROOT_PASSWORD: ${DB_ROOT_PASS:?}
    healthcheck:
      test:
        - CMD
        - bash
        - -c
        - mysqladmin --user=admin --password=${DB_PASS:?} ping | grep -cm1 'mysqld is alive'
      start_interval: 1s
      start_period: 420s
    volumes:
      - db:/var/lib/mysql

  wpscan:
    profiles:
      - CI
    image: wpscanteam/wpscan
    user: "root"
    depends_on:
      wordpress-config:
        condition: service_completed_successfully
    volumes:
      - ./reports:/reports
    command: >
      wpscan --url="http://wordpress" \
            --enumerate u,vp,vt \
            --clear-cache \
            --api-token ${WPSCAN_TOKEN:?}
            --output /reports/wpscan_report.txt
  wpscan-waiter:
    image: wordpress:cli
    profiles:
      - CI
    entrypoint: ["true"]
    depends_on:
      wpscan:
        condition: service_completed_successfully

volumes:
  wordpress:
  db: