# block xmlrpc.php and wp-cron.php
<FilesMatch "^(xmlrpc\.php|wp-cron\.php)$">
  Require all denied
</FilesMatch>

#hide Apache version and OS info
ServerTokens Prod
ServerSignature Off

#remove server headers
Header unset Server